app_admin_supplier:
    resource: |
        alias: app.supplier
        section: admin
        templates: "@SyliusAdmin\\Crud"
        except: ['show']
        redirect: update
        grid: app_admin_supplier
        permission: true
        vars:
            all:
                subheader: sylius.ui.manage_suppliers
                
            index:
                icon: audio description
    type: sylius.resource
